/**:
  ros__parameters:
    robot_base_frame: base_link
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.5
    progress_timeout: 15.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 0.2
    transform_tolerance: 0.3
    min_frontier_size: 0.35
    recovery_delta: 1.0
    target_prox_lim: 0.26
    goalpause_timeout: 2.0